sudo: required

language:
  - node_js
  - python

node_js:
  - 10

python:
  - "3.6"

services:
  - docker

before_scrip:
  - yarn install
  - pip install requests

# install:
#   - docker network create network-api
#   - docker-compose up --build -d

stages:
  - Tests
  - Deploy docker image stage
  - Deploy docker image prod
  - Upgrade rancher service

jobs:
  include:
    - stage: "Tests"
      name: "Tests"
      script:
        # run lint and tests
        -  yarn test
        - ./node_modules/.bin/codecov -t ${CODECOV_TOKEN}

    - stage: "Deploy docker image stage"
      name: "Deploy docker image stage"
      if: branch = devel
      script:
        # build docker image
        - docker build -t gymnasteg2019/frontend:homolog .

        # push image to Docker Hub
        - docker push gymnasteg2019/frontend:homolog

    - stage: "Deploy docker image prod"
      name: "Deploy docker image prod"
      if: branch = master
        # build docker image
        - docker build -t gymnasteg2019/frontend:prod .

        # push image to Docker Hub
        - docker push gymnasteg2019/frontend:prod

    - stage: "Upgrade service"
      name: "Upgrade service"
      if: branch = develop || branch = master
      script: python ./scripts/upgrade_service.py

after_script:
#   - docker-compose down
  - yarn posttest
