language: node_js

node_js:
  - 10

sudo: required

services:
  - docker

install:
  - docker network create network-api
  - docker-compose up --build -d

script:
  - docker exec -it web yarn test
  # - docker run -e CI=true frontend yarn run test

after_script:
  - docker-compose down
